### ISSUE TITLE
B2G OS & Chirimen Collaboration

### ISSUE THREAD

**Issue by kskarthik** [chirimen-oh/Support-And-FAQ#5]
Hello! I am from [B2G OS](https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS) community. You might already know that we are maintaining the smart phone part. 

Let's bridge the gap between our both communities by supporting each other & move forward :smiley:

**Comment by ghost** [comment]
@kskarthik hi,

about the code, "bridge the gap" means "use(move to) master branch", right?

**Comment by kskarthik** [comment]
yes! transition is done & it's fairly good for chirimen. Codebase has changed & all mozApi's are gone. Now work is ongoing on implementing web api's

Also some help to b2g os from code side is appreciated :-)

Our community is active porting the ROM's now & everything is working fine except the phone specific api's

Only dialer is working now, as it was turned to [chrome://](https://discourse.mozilla-community.org/t/why-gaia-apps-are-turned-to-chrome/8011)

**Comment by kskarthik** [comment]
@naobsd any update on this ?

**Comment by ghost** [comment]
@kskarthik we have no objection for joining B2G OS community, and moving our codebase to master.

but, I'm not sure what I(we) can do for B2G OS community. currently we are focusing on designing/implementing/using our Web APIs such as WebGPIO, WebI2C on CHIRIMEN board. our man power is very limited (for now), I guess it's very hard to do other things for B2G OS community such as improving common apis/apps in B2G OS.
(if someone in B2G OS community has interest about our work, probably we can prepare some CHIRIMEN boards...)

by the way, I think it will be better to use https://discourse.mozilla-community.org/c/b2g-os-participation for this discussion.

**Comment by kskarthik** [comment]
Here you go https://discourse.mozilla-community.org/t/b2gos-chirimen-collaboration/10749/1
